site:
  title: Harvester Documentation
  url: /
  start_page: v1.3@harvester-product-docs:en:index.adoc

content:
  sources:
  - url: ./
    branches: [main]
    start_paths: [docs/version-*]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  extensions:
    - '@asciidoctor/tabs'