= Installation
:id: index
:sidebar_label: Installation
:sidebar_position: 1

The following sections contain tips to troubleshoot or get assistance with failed installations.

== Logging into the Harvester Installer (a live OS)

Users can press the key combination `CTRL + ALT + F2` to switch to another TTY and log in with the following credentials:

* User: `rancher`
* Password: `rancher`

== Meeting hardware requirements

* Check that your hardware meets the link:../install/requirements.adoc#hardware-requirements[minimum requirements] to complete installation.

== Stuck in `+Loading images. This may take a few minutes...+`

Because the system doesn't have a default route, your installer may become "stuck" in this state. You can check your route status by executing the following command:

[,shell]
----
$ ip route
default via 10.10.0.10 dev mgmt-br proto dhcp        <-- Does a default route exist?
10.10.0.0/24 dev mgmt-br proto kernel scope link src 10.10.0.15
----

Check that your DHCP server offers a default route option. Attaching content from `/run/cos/target/rke2.log` is helpful too.

For more information, see link:../install/pxe-boot-install.adoc#dhcp-server-configuration[DHCP Server Configuration].

== Modifying cluster token on agent nodes

When an agent node fails to join the cluster, it can be related to the cluster token not being identical to the server node token.
In order to confirm the issue, connect to your agent node (i.e. with link:./os.adoc#how-to-log-in-to-a-harvester-node[SSH] and check the `rancherd` service log with the following command:

[,shell]
----
$ sudo journalctl -b -u rancherd
----

If the cluster token setup in the agent node is not matching the server node token, you will find several entries of the following message:

```shell
msg="Bootstrapping Rancher (v2.7.5/v1.25.9+rke2r1)"
